// elbruno.Doc2Code — assembles the user manual markdown from captured screenshots.
import * as fs from 'fs';
import * as path from 'path';

const screenshotFolder = path.resolve(__dirname, '..', '..', 'docs', 'screenshots');
const manualOutputPath = path.resolve(__dirname, '..', '..', 'docs', 'user-manual.md');

interface ManualEntry {
  imageFile: string;
  heading: string;
  blurb: string;
}

const manualSections: ManualEntry[] = [
  {
    imageFile: '01-home-idle.png',
    heading: 'Getting Started',
    blurb:
      'When you first open elbruno.Doc2Code the home screen shows the pipeline diagram, an upload area, and the console panel. No document is loaded yet — the pipeline nodes are idle.',
  },
  {
    imageFile: '02-file-selected.png',
    heading: 'Uploading a Document',
    blurb:
      'Click the upload area (or drag-and-drop a file) to select a requirements document. The filename appears once the file is accepted and ready for processing.',
  },
  {
    imageFile: '03-pipeline-diagram.png',
    heading: 'Pipeline Visualization',
    blurb:
      'The pipeline diagram displays each agent as a node: Analyst, Architect, Developer, Reviewer, Testing, and Documentation. Active nodes are highlighted while they process input.',
  },
  {
    imageFile: '04-console-panel.png',
    heading: 'Console Output',
    blurb:
      'The console panel streams real-time log messages from the backend via SignalR. Use it to monitor agent progress, warnings, and completion events.',
  },
  {
    imageFile: '05-settings-page.png',
    heading: 'Configuration',
    blurb:
      'Navigate to the Settings page to configure model endpoints, toggle tools, and adjust agent behaviour. Changes are persisted by the SettingsService.',
  },
  {
    imageFile: '06-agent-profiles.png',
    heading: 'Agent Profiles',
    blurb:
      'Expand an accordion panel on the Settings page to inspect and modify individual agent profiles, including system instructions and enabled tools.',
  },
];

function assembleManual(): string {
  const lines: string[] = [
    '# elbruno.Doc2Code — User Manual',
    '',
    'This manual is auto-generated from screenshots captured by the Playwright test suite.',
    '',
  ];

  for (const entry of manualSections) {
    const imageExists = fs.existsSync(path.join(screenshotFolder, entry.imageFile));
    lines.push(`## ${entry.heading}`);
    lines.push('');
    lines.push(entry.blurb);
    lines.push('');
    if (imageExists) {
      lines.push(`![${entry.heading}](screenshots/${entry.imageFile})`);
    } else {
      lines.push(`> _Screenshot \`${entry.imageFile}\` not yet captured — run the Playwright screenshot suite first._`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('Screenshots are auto-generated by the Playwright test suite.');
  lines.push('');

  return lines.join('\n');
}

const markdownContent = assembleManual();
fs.writeFileSync(manualOutputPath, markdownContent, 'utf-8');
console.log(`User manual written to ${manualOutputPath}`);
