<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\elbruno.Doc2Code.ServiceDefaults\elbruno.Doc2Code.ServiceDefaults.csproj" />
    <ProjectReference Include="..\elbruno.Doc2Code.Core\elbruno.Doc2Code.Core.csproj" />
  </ItemGroup>

</Project>
